---
language: node_js

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install ember-cli@$EMBER_CLI_VERSION
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

env:
  - EMBER_CLI_VERSION=latest
  - EMBER_CLI_VERSION=0.1.5
  - EMBER_CLI_VERSION=0.1.2
  - STANDIN_VAR=nothing